use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/NoNameOrganazation/LNSpec.git'

platform :ios, '10.0'

target 'LNUserCenterModule_Example' do
  pod 'LNUserCenterModule', :path => '../'
  
#  pod 'LNModuleCore', :path => '../../LNModuleCore'
#  pod 'LNModuleProtocol', :path => '../../LNModuleProtocol'
#  pod 'LNCommonKit', :path => '../../LNCommonKit'
#
  
  target 'LNUserCenterModule_Tests' do
    inherit! :search_paths

    
  end
end
