use_frameworks!

platform :ios, '10.0'

target 'LNUserCenterModule_Example' do
  pod 'LNUserCenterModule', :path => '../'

  target 'LNUserCenterModule_Tests' do
    inherit! :search_paths

    
  end
end
